### ISSUE TITLE
Error when sending email with v1.0.1

### ISSUE THREAD

**Issue by dronsfield** [keystonejs/keystone-email#7]
I get the error below when trying to send email with v1.0.1. Unsure how to solve.

I reverted to v1.0.0 and everything works fine.

`TypeError: this.transport is not a function`
`at <MY_PATH>\node_modules\keystone-email\lib\Email.js:111:8`
`at <MY_PATH>\node_modules\keystone-email\lib\Email.js:66:3`
`at Immediate._onImmediate (<MY_PATH>\node_modules\express-handlebars\lib\utils.js:26:13)`
`at processImmediate [as _immediateCallback] (timers.js:383:17)`

**Comment by mxstbr** [comment]
Are you passing in the transport? 

```JS
new Email('template.pug', {
  transport: 'mailgun', // or 'mandrill' 
}).send();
```

**Comment by dronsfield** [comment]
Yep, using mandrill. Everything works fine with v1.0.0, emails are being
sent.

**Comment by mxstbr** [comment]
Can you copy and paste the code? It's kind of hard to diagnose like this!
